[phases.setup]
nixPkgs = ["python312"]

[phases.install]
cmds = ["pip install -r requirements.txt", "pip install -e ."]

[start]
cmd = "uvicorn kitkat.main:app --host 0.0.0.0 --port ${PORT:-8000}"

[variables]
PYTHONPATH = "src"
